[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00C9A7"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#E0E0E0"
font = "sans serif"
